### PR TITLE
Remove extra logging

### PR DESCRIPTION
**Pull request by emveepee**
During conversion PR some logging messages were added to release build which should not have been included

### CODE REVIEW

**Comment by emveepee** [comment]
@oddstr13 @crobibero  Can this please be part of the 10.70 release.  The changes made to PR 12 will add unnecessary log information and could be spammy.

Also what is the recommended method for dealing with the file/assembly minor version number.

**Comment by crobibero** [comment]
We only update the major version number, but in this case the plugin hasn't been released so no need to update it.
IMO the debug logs should stay included so they don't need to be re-added in future updates

**Comment by emveepee** [comment]
> 
> 
> We only update the major version number, but in this case the plugin hasn't been released so no need to update it.
> IMO the debug logs should stay included so they don't need to be re-added in future updates

I basically removed logging of information that I added for tracing during the conversion not for debugging.  In my original submit they were not going to logger the were System.Diagnostics messages.  These should have been removed in PR 12 not changed to logger output.   

If there is a review in the future it will be to changes some logs from system to plugin specific debug logging.  I haven't seen enough user logs to know what belongs were.

**Review by oddstr13 — APPROVED** [review]
I saw the logging would be spammy, but it's all debug which doesn't get logged by default, so I didn't care enough to hold up the other pullrequest over it.

Thanks for going the extra mile of cleaning it up :smiley: 

As for versioning, the release hasn't been tagged yet.

**Review by crobibero — APPROVED** [review]

**Pull request merged**
